name: maven-test
on: push
jobs:
 job1:
  runs-on: ubuntu-latest
  steps:
   - name: checkout code
     uses: actions/checkout@v3
   - name: setup java sdk
     uses: actions/setup-java@v1
     with:
      java-version: 1.8
   - name: creating maven folder
     run: mvn -B archetype:generate -DarchetypeGroupId=org.apache.maven.archetypes -DgroupId=com.mycompany.app -DartifactId=my-app
