name: maven-test
on: push
jobs:
 job1:
  runs-on: ubuntu-latest
  steps:
   - name: checkout code
     uses: actions/checkout@v3
   - name: setup java sdk
     uses: actions/setup-java@v1
     with:
      java-version: 1.8
   - name: check maven version
     run: mvn -v
   - name: build package from pom
     run: mvn -B package --file pom.xml
   - name: change directory to target and list files
     run: |
      cd target
      ls -a
